### ISSUE TITLE
npm hangs during install of ffmpeg-binaries

### ISSUE THREAD

**Issue by ViralPanda** [Hackzzila/node-ffmpeg-binaries#1]
Hello,

My npm gets stuck while installing ffmpeg-binaries. Attached are the last three lines that I got in verbose mode of npm.

```
npm http fetch GET https://registry.npmjs.org/ffmpeg-binaries/-/ffmpeg-binaries-3.2.2-3.tgz
npm http fetch 200 https://registry.npmjs.org/ffmpeg-binaries/-/ffmpeg-binaries-3.2.2-3.tgz
[    ..............] \ loadRequestedDeps: http fetch 200 https://registry.npmjs.org/ffmpeg-binaries/-/ffmpeg-binaries-3
```

**Comment by ViralPanda** [comment]
It worked after ~30 mins!

**Comment by Hackzzila** [comment]
Huh, it seems like an npm problem. The big archives are only on github and should not be on npm. I am going to rewrite this (probably right now) to be more lightweight and fast.

**Comment by benjamingr** [comment]
@Hackzzila any ETA on that? It takes forever to install

**Comment by rmonaghanjr** [comment]
wait ETA means Estimated Time of Arrival...
