### ISSUE TITLE
npm install fails: Unhandled rejection Error: incorrect header 

### ISSUE THREAD

**Issue by Zvika88** [Hackzzila/node-ffmpeg-binaries#13]
This used to work fine few weeks ago. It now produces the following error message:

Unhandled rejection Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:370:17)

**Comment by sh-dave** [comment]
Same here on
- Win10, npm 5.5.1
- Ubuntu 16.04, npm 6.1.0

**Comment by Hackzzila** [comment]
Versions before 4.0.0 are now completely broken. Version 4.0.0 should work fine. v4 will not yet work with discord.js/prism-media until my PR is merged.
