### ISSUE TITLE
Security question

### ISSUE THREAD

**Issue by kirtansakariya** [Hackzzila/node-ffmpeg-binaries#17]
I'm using ffmpeg-binaries for a discord bot that I'm working on. There's something that I'm concerned about though. When I installed ffmpeg-binaries, I found that there were a couple of security issues related to a dependency of ffmpeg-binaries. There were two packages that these security issues. The chain of packages is: `ffmpeg-binaries > decompress-tarxz > lzma-native > node-pre-gyp > request > hawk > hoek` and `ffmpeg-binaries > decompress-tarxz > lzma-native > node-pre-gyp > request > stringstream`. Do you know if it is possible to implement a solution in regards to this on the side of ffmpeg-binaries?

**Comment by kirtansakariya** [comment]
Found an alternative, closing the issue.

**Comment by progamax** [comment]
Hello,
Which alternative have you found ? I have the same problem as you

**Comment by progamax** [comment]
> 
> 
> Found an alternative, closing the issue.

Hello,
Which alternative have you found ? I have the same problem as you

**Comment by kirtansakariya** [comment]
@progamax My alternative was using a package that did not use ffmpeg-binaries as a dependency. So it wasn't really a solution to this security issue, but more that I just found a package that used a different dependency than this one. Is ffmpeg-binaries a dependency to another package that you're using?

**Comment by progamax** [comment]
Yes, I use discord.js and ffmpeg-binairies is a dependency of it

**Comment by kirtansakariya** [comment]
@progamax Sorry for the late reply. Would you be able to post your `package.json`? I'll compare with mine and see if I can compare the packages that we're both using.

**Comment by progamax** [comment]
```{
  "name": "discordbot",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node index.js",
    "dev": "nodemon index.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bufferutil": "^4.0.1",
    "discord.js": "github:discordjs/discord.js",
    "erlpack": "^0.1.2",
    "ffmpeg-binaries": "^4.0.0",
    "libsodium-wrappers": "^0.7.4",
    "node-opus": "^0.3.1",
    "opusscript": "0.0.6",
    "sodium": "^3.0.2",
    "uws": "^100.0.1"
  },
  "devDependencies": {
    "nodemon": "^1.18.11"
  }
}
```
I just changed the package discord.js to its master branch to avoid some bugs but this is my package.json

**Comment by kirtansakariya** [comment]
Oh okay. What I did was I just removed `ffmpeg-binaries` and download `ffmpeg` and used that for my bot. Are you running your bot on windows? I have mine on ubuntu through an ec2 instance from aws.

Link for `ffmpeg`: http://ffmpeg.org/download.html

**Comment by kirtansakariya** [comment]
@progamax Did that help resolve your issue?
