### ISSUE TITLE
Problem installing ffmpeg-binaries

### ISSUE THREAD

**Issue by tttedu304** [Hackzzila/node-ffmpeg-binaries#19]
Hey, I'm trying to install FFmpeg-binaries but I get an error, I tried some solutions that people recommended me, but still doesn't work. 
![screenshot_56](https://user-images.githubusercontent.com/42099005/52179325-16f9c480-27a7-11e9-855c-45edaf70143f.png)
![screenshot_57](https://user-images.githubusercontent.com/42099005/52179326-16f9c480-27a7-11e9-93b1-3bdd0198e151.png)
![screenshot_58](https://user-images.githubusercontent.com/42099005/52179327-16f9c480-27a7-11e9-959a-2189d983fbd4.png)

**Comment by tttedu304** [comment]
I can install ffmpeg using npm i ffmpeg, but as I said the problem is with ffmpeg-binaries.

**Comment by kiikoh** [comment]
Same issue here

**Comment by cloewen8** [comment]
Same. Identical line numbers, slightly different versions for the other dependencies.

**Comment by ray-1337** [comment]
same here.

**Comment by ray-1337** [comment]
me like, **FFMPEG Not Found**, but installed.

**Comment by keru1264** [comment]
weird, never had this problem with `lzma-native`. fixing few broken links to binaries inside of [install.js](https://github.com/keru1264/node-ffmpeg-binaries/blob/master/install.js) was enough to make ffmpeg work on heroku.
