### ISSUE TITLE
npm install failing at ffmpeg-binaries

### ISSUE THREAD

**Issue by OGNova** [Hackzzila/node-ffmpeg-binaries#5]
Hey there,

I recently made a package for a project I'm creating, and after testing it on Windows and having it work semi-fine, I decided to transfer it to my Linux VPS to further test in my project. Upon trying to install said package, the installation fails at `ffmpeg-binaries@3.2.2-3 install: node install`.

The error says that it's most likely not a problem with npm, which leads me to believe that it's an issue with ffmpeg-binaries itself. The full error message is this, http://prntscr.com/g4sp4d, and the complete log is this. http://how.evie-banned.me/guvigoheji.pl Apologies for the weird url, Hastebin is broken yet again.

If it's not a problem with ffmpeg, would you happen to have any clue what it is?

**Comment by panikdkernel** [comment]
I am getting the same error

**Comment by JvandeKraats** [comment]
Same issue here when trying to do this:

'CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> ffmpeg-binaries@3.2.2-3 install C:\Users\j_v_d\Documents\Visual Studio Code\Projects\discordbot\node_modules\ffmpeg-binaries
> node install

npm WARN discord.js@11.2.1 requires a peer of bufferutil@^3.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of erlpack@hammerandchisel/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of node-opus@^0.2.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of opusscript@^0.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of sodium@^2.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of libsodium-wrappers@^0.5.4 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.2.1 requires a peer of uws@^0.14.5 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js-commando@0.9.0 requires a peer of sqlite@^2.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN discordbot@1.0.0 No description
npm WARN discordbot@1.0.0 No repository field.

npm ERR! file C:\WINDOWS\system32\cmd.exe;C:php;
npm ERR! path C:\WINDOWS\system32\cmd.exe;C:php;
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe;C:php;
npm ERR! ffmpeg-binaries@3.2.2-3 install: `node install`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe;C:php; ENOENT
npm ERR!
npm ERR! Failed at the ffmpeg-binaries@3.2.2-3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myUser\AppData\Roaming\npm-cache\_logs\2017-11-08T20_49_28_889Z-debug.log

**Comment by rmonaghanjr** [comment]
I'm getting the same thing, but the installation continued and was successful. @Hackzzila please look at this

**Comment by Hackzzila** [comment]
The install script was overhauled, hopefully there are no issues now.

**Comment by OGNova** [comment]
I'll be honest, I forgot that I had opened this issue. I found out after opening the issue that it wasn't actually a problem with the package, and was rather an error with the newly released (at the time) npm 5.
