### ISSUE TITLE
Stuck while installing

### ISSUE THREAD

**Issue by SXQHex** [Hackzzila/node-ffmpeg-binaries#7]
When i try to install it it stucks
![adsiz5](https://user-images.githubusercontent.com/33909965/33146310-af386a3e-cfd4-11e7-8879-5234a4c69685.png)
this window is about 20 min same...

**Comment by iSuslov** [comment]
+1

**Comment by rmonaghanjr** [comment]
yup

**Comment by RytardCodes** [comment]
This happened to me as well, i did a fix. Install the .zip File of FFMPEG-BINARIES on this Github Repo
Then extract it, and rename the folder of the extracted file to ffmpeg-binaries.
Once done that, put it in node-modules, then it will be installed. ( File is 200mb+ )

**Comment by Hackzzila** [comment]
There is not much I can do about this, it may have been because of the module's size. In 4.0.0 the binaries are downloaded remotely so the module is very small. 4.0.0 will be released soon.
